flags:
  time-locale-compat:
    old-locale: false
extra-deps:
- StateVar-1.1.1.0
- HUnit-1.6.0.0
- QuickCheck-2.9.2
- aeson-1.2.0.0
- aeson-qq-0.8.1
- ansi-terminal-0.6.2.3
- async-2.2.1
- attoparsec-0.13.1.0
- base-compat-0.9.3
- base-orphans-0.6
- base64-bytestring-1.0.0.1
- bifunctors-5.5.2
- cabal-doctest-1.0.6
- call-stack-0.1.0
- comonad-5.0.3
- contravariant-1.4.1
- cpphs-1.20.5
- data-default-class-0.1.2.0
- distributive-0.5.3
- dlist-0.8.0.2
- fail-4.9.0.0
- hashable-1.2.7.0
- haskell-src-exts-1.20.2
- haskell-src-meta-0.8.0.2
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- hspec-expectations-0.8.2
- integer-logarithms-1.0.2.1
- lens-family-1.2.1
- lens-family-core-1.2.1
- lens-labels-0.2.0.1
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- parsec-3.1.13.0
- polyparse-1.12
- primitive-0.6.4.0
- proto-lens-0.3.1.0
- proto-lens-protoc-0.3.1.0
- profunctors-5.2.2
- quickcheck-io-0.2.0
- random-1.1
- safe-0.3.14
- scientific-0.3.5.2
- semigroups-0.18.3
- setenv-0.1.1.3
- syb-0.7
- tagged-0.8.5
- tf-random-0.5
- th-abstraction-0.2.6.0
- th-expand-syns-0.4.4.0
- th-lift-0.7.10
- th-lift-instances-0.1.11
- th-orphans-0.13.3
- th-reify-many-0.1.6
- time-locale-compat-0.1.1.3
- transformers-0.5.5.0
- transformers-compat-0.5.1.4
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vector-0.12.0.1
- void-0.7.2
resolver: ghc-8.4.2
