flags:
  time-locale-compat:
    old-locale: false
extra-deps:
- HUnit-1.6.0.0
- QuickCheck-2.9.2
- StateVar-1.2
- aeson-1.2.0.0
- aeson-qq-0.8.1
- ansi-terminal-0.6.2.3
- attoparsec-0.13.1.0
- base-compat-0.9.3
- base-orphans-0.6
- base64-bytestring-1.0.0.1
- bifunctors-5.5.2
- cabal-doctest-1.0.6
- call-stack-0.1.0
- comonad-5.0.6
- contravariant-1.5.2
- distributive-0.5.3
- dlist-0.8.0.2
- happy-1.19.9
- hashable-1.2.7.0
- haskell-src-exts-1.20.3
- haskell-src-meta-0.8.1
- hspec-2.4.8
- hspec-core-2.4.8
- hspec-discover-2.4.8
- hspec-expectations-0.8.2
- integer-logarithms-1.0.2.2
- lens-family-1.2.3
- lens-family-core-1.2.3
- mtl-2.2.1
- parsec-3.1.13.0
- primitive-0.6.4.0
- proto-lens-0.5.0.0
- proto-lens-protoc-0.5.0.0
- proto-lens-runtime-0.5.0.0
- profunctors-5.2.2
- quickcheck-io-0.2.0
- random-1.1
- safe-0.3.14
- scientific-0.3.5.3
- semigroups-0.18.3
- setenv-0.1.1.3
- syb-0.7
- tagged-0.8.6
- tf-random-0.5
- th-abstraction-0.2.11.0
- th-expand-syns-0.4.4.0
- th-lift-0.8.1
- th-lift-instances-0.1.11
- th-orphans-0.13.3
- th-reify-many-0.1.6
- time-locale-compat-0.1.1.3
- transformers-0.5.6.2
- transformers-compat-0.5.1.4
- unordered-containers-0.2.9.0
- uuid-types-1.0.3
- vector-0.12.0.1
- void-0.7.2
resolver: ghc-8.6.5
