resolver: lts-20.0
extra-deps:
  # https://github.com/haskell-unordered-containers/unordered-containers/pull/317/
  # breaks our checksums, stick to the version before it
- unordered-containers-0.2.15.0
